### ISSUE TITLE
SFTP Enhancements

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#114]
There are too many issues about SFTP. 
This issue list all enhancements needed asap :

- [ ] Support for move and copy https://github.com/isontheline/pro.webssh.net/issues/57
- [ ] Able to download a file through SFTP https://github.com/isontheline/pro.webssh.net/issues/87
- [ ] Moving/copying files from iPad to server https://github.com/isontheline/pro.webssh.net/issues/113
