### ISSUE TITLE
Ability to support "badges" on terminal

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#1177]
# Feature description
Like iTerm2, ability to support "badges" :
* https://iterm2.com/documentation-badges.html

![](https://iterm2.com/images/Badge.png)
<img width="488" alt="Image" src="https://github.com/user-attachments/assets/86337277-c507-4e2d-8bb2-d5079a6e6eb2" />

# TODOs
- [x] Create documentation page
- [ ] Variable expansion : (doing later, please ask @isontheline if needed)
  - [ ] Username
  - [ ] Hostname
  - [ ] connection name
- [x] Ability to define from ssh_config :
  - [x] colour
  - [x] size
  - [x] Position
  - [x] Content
- [x] Escape Sequence. The badge may be set with the following control sequence: `OSC 1337 ; SetBadgeFormat=Base-64 encoded badge format ST`
  - [x] `printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "Awesome" | base64)`

**Comment by isontheline** [comment]
Now available inside latest beta release : https://testflight.apple.com/join/QSrBK59z
