### ISSUE TITLE
WoL : Wake-On-Lan

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#154]
# Todo
- [x] Add new connection field : MAC Address (and port?)
- [x] Add new contextual menu item : Wake Up
- [x] Add documentation about "WoL feature"

# To watch 
* https://github.com/gumb0/wol.cpp
* https://github.com/holzschu/ios_system/issues/98
* https://github.com/holzschu/network_ios/blob/master/wol.cpp
* https://github.com/holzschu/network_ios/releases

# Swift Libraries
* https://github.com/jesper-lindberg/Awake
* https://github.com/feritbolezek/WakeOnLan

**Comment by isontheline** [comment]
# Very useful app
It would be cool if you could implement a wol tool ;)

by **Tiku2021** on the *App Store*

**Comment by isontheline** [comment]
Does a Wake On Lan feature is still welcome?
With a GUI or inside mashREPL?

**Comment by bpeterme** [comment]
inside mashREPL would be fine for me, if this is not a widely requested feature. Although it would make sense implement it as a GUI feature.

I would like to second the request for a feature to send WOL packets to my home network. The idea is that I want to ssh into my server on demand, but I don’t wish lo leave the server on all day. I'm currently using a separate app for WOL, but I think it would be thematically very close and convenient to have such a feature in WebSSH.

**Comment by isontheline** [comment]
@bpeterme I prefer to start with GUI for WOL, it will be simpler

**Comment by isontheline** [comment]
@bpeterme Could you share your current WOL app you use?

**Comment by bpeterme** [comment]
It‘s a very simple iOS app called „Wake Me Up“.

**Comment by isontheline** [comment]
Thank you @bpeterme 🙏

I will implement WOL "soon"

**Comment by isontheline** [comment]
Hey 👋

WoL is coming! 🚀
https://webssh.net/documentation/help/networking/wake-on-lan/

Available tomorrow ✌️

**Comment by isontheline** [comment]
Now available inside latest beta release : https://testflight.apple.com/join/QSrBK59z

**Comment by bpeterme** [comment]
tested it and works like a charm. Thank you so much!
