### ISSUE TITLE
Migrating from paid to free with In-App Purchases

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#23]
**Will not concern all WebSSH users who have already bought the app in the past! (bought before 2020-08-29)**

# In-App Purchases
- [ ] ~(Tier 1) Network tools (ping, whois, traceroute)~
- [ ] (Tier 1) Additional fonts for the SSH terminal #60 
- [ ] (Tier 2) Export / Import database #43 
- [ ] (Tier 2) Copy / Move files and folders with SFTP #57 
- [x] (Tier 3) Unlimited connections : 1 allowed by default
  - [ ] Display ads (side projects?)
- [ ] (Tier 3) VPN over SSH #25 
- [ ] (Tier 3) iCloud Sync #43 
- [ ] (Tier 3) Unlock premium commands #48 
- [ ] (Tier 5-9) Full application unlock : like WebSSH Pro, so all currents and futures In App Purchases forever

# Checks
- [x] Check creation date of webssh.db
- [x] Prevent cloning if not unlimited

**Comment by isontheline** [comment]
https://fluffy.es/migrate-paid-app-to-iap/

**Comment by avalonix** [comment]
I think it is quite possible to switch to such a model.  the main thing is not on the subscription model.  ) the main thing is to decide which functionality will be provided for free, and which in the full version.  can add some more functions to the application.

**Comment by isontheline** [comment]
@avalonix Thanks for your feedback!

In order to don't hurt anybody, a possible freemium model could be :
- All features are available for everyone
- But free users can only add 1 (one) connection per ssh/sftp/tunnel

**Comment by avalonix** [comment]
good too!

**Comment by baderalnhdy** [comment]
Hi

**Comment by isontheline** [comment]
Hi @baderalnhdy 👋

**Comment by isontheline** [comment]
At this time I think that WebSSH will only have "Unlimited" IAP.

**Comment by Riyadh4012** [comment]
Riyadh
