### ISSUE TITLE
Terminal Virtual Keyboard Enhancements

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#37]
- [x] #30 : Floating Keyboard and/or Split View : Keyboard focus problem
- [x] #44 : Keyboard : can't hide it by using the bottom right button
- [x] #99 : Keep Keyboard active on ssh reconnect
- [x] #111 : Lots of instant output will exceed keyboard boundary

**Comment by svenh0** [comment]
After this change the terminal use after open only the half area. 
The terminal log is fill only to the middle of the window.
All lines are used only after show/hide the virtual keyboard.

iPad Pro 11 (IOS 13.6)
WebSSH 14.1.10 TestFlight

**Comment by isontheline** [comment]
I have the same behavior/bug

@svenh0 I will revert this issue asap and so it will show the keyboard by default again as it doesn't fix #32 unfortunately.

**Comment by svenh0** [comment]
Thanks. 
But if would calculate correct lines count on open terminal, i can live with default hide keyboard. 
An option in the setup "show keyboard on open terminal" would be the best. 

Can you check also the problem, that most i can't close the virtual keyboard with the hide-button right down in the keyboard (the button in the right down corner to close the keyboard). 
On this way it works always:
1. close keyboard
2. press button top right to toggle on/off the full screen mode (the third button in the right menu with the 4 arrows)
3. press button top right to show keyboard
4. press button down right in the keyboard to close keyboard (this works)
If you open again the keyboard on second time, it's not work:
5. press button top right to show keyboard
6. press button down right in the keyboard to close keyboard (don't works)

Close keyboard with the button in the virtual keyboard works only if you toggle fullscreen before open the keyboard.

**Comment by isontheline** [comment]
1. OK I will fix the bad lines count at startup (prior to showing the keyboard)

2. OK too, I will fix the bug that prevent the keyboard to be hided by using the bottom right button of the virtual keyboard

**Comment by isontheline** [comment]
Working on a fix of #44
Will be available in 14.8.11

**Comment by isontheline** [comment]
Working on #30
