### ISSUE TITLE
SSH URL Link Scheme (aka Deep Linking)

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#557]
We are using a website with a dashboard where our customers are listed with some default infos, their websites and their servers. We implemented a little button behind every server IP / Hostname to connect to this server directly via Putty (ssh://<serverip/hostname>). 

The only current alternative that supports this is Termius, but we do not want to use a cloud based service.

> Are you wanting it on iOS or macOS? 

We'd need it mostly for iOS/iPadOS, but a few could use it on macOS.

> Are you using a lot of ssh:// links on day to day use?

We are currently rolling out iPads for our field service staff and this could immensely help them, as they won't need to browse a huge list of entries or enter the IP manually.

_Originally posted by @Thunderhawk2001 in https://github.com/isontheline/pro.webssh.net/discussions/554#discussioncomment-2271572_

# Tasks
- [x] SSH Scheme
- [ ] ~~SFTP Scheme~~ (Later, another issue needed)
- [ ] ~~Ability to launch a command at connection startup?~~(What about security risks?)
- [x] Ask if user accepts to launch the connection. Permission could be granted definitively inside settings.
- [ ] Check if user can add more connections (PRO)
- [x] Documentation about this feature => ?save=true&name=Awesome&group=Earth&tags=super,tags,too

**Comment by isontheline** [comment]
Hello @Thunderhawk2001 👋

Are you still interested in this feature?

**Comment by Thunderhawk2001** [comment]
Hi there 😀

Thanks for still considering this. Yes, we actually could very much still use this 😅

**Comment by isontheline** [comment]
Thanks for your feedback 🙏

It will help me to drive the roadmap

**Comment by isontheline** [comment]
From **milo2012** on *Discord* :
> Does webssh supports iOS url scheme ?
> I am using remote.it and it supports termius app but I would prefer to use webssh instead
> ![Image](https://user-images.githubusercontent.com/44212923/219154289-3f5332f0-439e-4a95-b71d-308a9dabfb96.png)

Thanks for your feedback 🙏
I’ve already planned to work on iOS Schemes in the next few weeks. A possible ETA could be the end of march.

**Comment by isontheline** [comment]
Hello @Thunderhawk2001 👋

I'm currently implementing this feature that you should be released in a few days now.

Are you still using WebSSH on your side?
If so could you tell me if you was using [Termius "?id="](https://support.termius.com/hc/en-us/articles/4406192748313-Deep-Linking-on-iOS) parameter inside your links?

**Comment by Thunderhawk2001** [comment]
Hi @isontheline 👋 

That's very good to hear :) Thank's a lot.
Yes we are still using WebSSH and really looking forward for this feature.

No, we currently do not use the "id?=" parameter.

Have a great day/evening.

**Comment by isontheline** [comment]
@Thunderhawk2001 Will you be able to change links scheme on your side?

I'm asking because "ssh://" scheme is already taken by Termius and so it will be launched instead of WebSSH.

**Comment by Thunderhawk2001** [comment]
@isontheline  Yes, It would be possible to change it. But as we are not using Termius, there would be no problem on our side with keeping it the same scheme. :)

**Comment by isontheline** [comment]
@Thunderhawk2001 Greet so I will use the ssh:// scheme so 😀

I will come back to you in the upcoming days.

See you

**Comment by isontheline** [comment]
First beta now available : https://testflight.apple.com/join/QSrBK59z

**Comment by mbierman** [comment]
Exciting!  I love deeplinks. Not sure how I will use this yet, but I may find a way!  Thank you.

**Comment by isontheline** [comment]
@mbierman Thank you!
This is a first try, please report any issue you want to be fixed.

Documentation will come tonight with mandatory and optional parameters.

**Comment by isontheline** [comment]
A little bug prevent to be used under iPhone. Will be fixed soon.

Main targets are macOS / iPad but iPhone will be also supported.

**Comment by isontheline** [comment]
A first try for documentation is here : https://webssh.net/documentation/help/howtos/use-deep-linking/

**Comment by mbierman** [comment]
Is the macOS version ready? I actually realized that this feature will be tremendously helpful to me and I'm excited about trying it.

**Comment by isontheline** [comment]
@mbierman Yes macOS is also supported on latest TestFlight release but only one app can handle ssh:// links at a time

Yet there is no way to prevent to open in split view on iPad OS. I need to improve my implementation to check if a connection is already opened before to split or not.

**Comment by mbierman** [comment]
How do you change the default app for the ssh prototol?

**Comment by isontheline** [comment]
@mbierman 

> How do you change the default app for the ssh prototol?

Seems not "possible" : https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app

<img width="645" alt="image" src="https://user-images.githubusercontent.com/44212923/222985374-181a5890-ae00-4d55-b6fe-fb7bdec9ea6f.png">

> Out of couriosity why not use an app specific prototol for deeplinking like webssh:// ?

I can implement a scheme fallback but if another app implements "webssh://" we are also out of luck.

**Comment by mbierman** [comment]
OK good to know I wasn't losing my mind. 

In my experience, app names seem to usually work as deeplink protocols. IF you are really worried, you could try "prowebssh" or some such. Another option, if it is possible, is default to webssh but let the user change it via a setting? Is that doable?

**Comment by isontheline** [comment]
@mbierman 
I'm not worried I just think that Apple should provide a way to change the scheme assignation.

User can't change it via a setting because the schemes need to be set at build time, not at runtime.

ssh:// scheme need to be available as it is used already inside several customers HTML pages.
I could add another (webssh://) if user need / want to stick with another app under ssh:// one

Would you like I add webssh:// ?

**Comment by mbierman** [comment]
Apple can't make this settable. Sure, for common protocols like ssh they could, but that is also a long list of possibilities and most customers wouldn't know what to do with it. But imagine a random app that wants to allow launching with a deep link that doesn't use a special standard protocol. This is why there are Universal Links https://developer.apple.com/ios/universal-links/ that are app specific. I don't remember if Apple makes the developer register them to make sure they are unique. Having an app centric url is critical especially when a) you are cross platform and b) the platforms don't allow the user to set them.

**Comment by isontheline** [comment]
Universal Links are more suitable when used with https scheme because it force app to be opened when user browse the app website (facebook, twitter, etc). Here it's not the case with SSH handling.

If users want to open deep links they know that they want so Apple could open a modal : which app would you like yo use for ssh:// ?

Why a scheme is sticked with the first app (with scheme handling) installed on the device?

But that's other stories... 😅

Will you use ssh:// scheme or would you like I add webssh:// also?

**Comment by mbierman** [comment]
Mac users will need both since they can't set it. 

For what it is worth I will respectfully disagree with you (maybe?) 

Actually, http/s can be set by the user on ios and macos now. So that is a case where there is no need for a universal link. It is precisely for custom things that a universal link is needed. In this case, the user isn't calling SSH.  They are calling webSSH which knows what to do with the URL. That seems to me exactly the right thing to be doing. 

I think you are optimizing a different case (which I think is rare?) which is clicking on a web page to open a secure shell. I don't think anyone does that or should do that. Seems very insecure to me since you don't know what may be hiding in a link.

**Comment by Thunderhawk2001** [comment]
> Hello @Thunderhawk2001 👋
> 
> I'm almost done.
> 
> The "user" and "host" fields are mandatory inside WebSSH. So a minimal URL could be : ssh://user@host
> 
> Right now if you don't provide the user WebSSH will complain. A first beta release will be available in a few hours.

Hello @isontheline ,

Tried the beta just now and it's working like a charm. Only "issue" I'm facing is, the app asks for a password. Is there a way to tell the app to always first try to use the certificate (and then ask for password, if not working)? Or just "always use the certificate" ?

Thanks a lot for the work !❤️

**Comment by isontheline** [comment]
Hello @Thunderhawk2001 👋

Thanks for trying out 🙏

Yet you can't specify to use pkey.
Will you be able to specify the key name inside your links?

Instead of trying a lot of pkeys a user may have, I would like a solution like this : 
ssh://user@host:port/?key=AWESOME

And AWESOME will be the pkey name inside WebSSH keys manager.

This solution could be implemented in a few hours.

Are you okay?

**Comment by Thunderhawk2001** [comment]
Hi @isontheline 

I'll talk with our programmer about this, but I think this will be possible.
Do we have to use the "whole" name with extension or just the name? e.g.  "MySuperCoolCertificate.ppk" or just "MySuperCoolCertificate" .

**Comment by isontheline** [comment]
@Thunderhawk2001 The name inside this field :


![Image](https://user-images.githubusercontent.com/44212923/223838926-774a4369-c981-429d-a107-10aaf31922ec.png)

**Comment by isontheline** [comment]
I'm closing this issue as the App Store release is available since two days ago.

Any new issues about any problem are welcome!

**Comment by isontheline** [comment]
The issue about ability to use a private key with deep links is opened here : https://github.com/isontheline/pro.webssh.net/issues/838
