### ISSUE TITLE
macOS : Use Split View to enhance user's feel

### ISSUE THREAD

**Issue by isontheline** [isontheline/pro.webssh.net#573]
# Tasks
- [x] Removing LIExposeController
- [x] Implements Double/Three column Split View : https://developer.apple.com/tutorials/mac-catalyst/displaying-the-sidebar
- [x] Blur views when locked
- [x] Change language
- [x] User activity : ability to launch mashREPL from app icon menu (UserActivitiesHelper)
- [x] Update app description about macOS availability : https://github.com/isontheline/pro.webssh.net/issues/322#issuecomment-1080349600
- [x] Tap_Plus_Button_To_Add_Your_First_Connection => To add a connection
- [x] "Help" menu => Show in a new WebSSH "inside" window
- [x] Open all toolbar items inside a new window
- [x] Removing HUD for shortcuts. Replace with popup menu. https://github.com/isontheline/pro.webssh.net/issues/487
- [x] macOS Sidebar
- [x] View > Zoom In / Out
- [x] Ping / Whois screens are not properly rendered (textfield)
- [x] SFTP Sidebar
- [x] TUNNEL Sidebar
- [x] Right clic > close connection
- [x] didSelectSessionItem > focus()

# Helps
* https://zachsim.one/blog/2019/8/4/customising-the-menu-bar-of-a-catalyst-app-using-uimenubuilder
* https://larztech.com/posts/2020/06/catalyst/
